alter table campaign_user add column c_seq bigint default 0;
alter table copyitem_user add column c_seq bigint default 0;
alter table copyitem_user add column s_seq bigint default 0;
alter table custom add column c_seq bigint default 0;
alter table giveitem_checkrfid add column c_seq bigint default 0;
alter table giveitem_checkrfid add column locale character varying(10);
alter table item_present add column c_seq bigint default 0;
alter table item_present add column to_c_seq bigint default 0;
alter table user_item add column c_seq bigint default 0;

ALTER TABLE campaign_user ALTER COLUMN rfid DROP NOT NULL;
ALTER TABLE copyitem_user ALTER COLUMN rfid DROP NOT NULL;
ALTER TABLE custom ALTER COLUMN rfid DROP NOT NULL;
ALTER TABLE item_present ALTER COLUMN rfid DROP NOT NULL;
ALTER TABLE item_present ALTER COLUMN to_rfid DROP NOT NULL;
ALTER TABLE user_item ALTER COLUMN rfid DROP NOT NULL;
ALTER TABLE user_item_history ALTER COLUMN rfid DROP NOT NULL;

alter table user_item_history add column c_seq bigint default 0;
alter table user_item_history_200901 add column c_seq bigint default 0;
alter table user_item_history_200902 add column c_seq bigint default 0;
alter table user_item_history_200903 add column c_seq bigint default 0;
alter table user_item_history_200904 add column c_seq bigint default 0;
alter table user_item_history_200905 add column c_seq bigint default 0;
alter table user_item_history_200906 add column c_seq bigint default 0;
alter table user_item_history_200907 add column c_seq bigint default 0;
alter table user_item_history_200908 add column c_seq bigint default 0;
alter table user_item_history_200909 add column c_seq bigint default 0;
alter table user_item_history_200910 add column c_seq bigint default 0;
alter table user_item_history_200911 add column c_seq bigint default 0;
alter table user_item_history_200912 add column c_seq bigint default 0;
alter table user_item_history_201001 add column c_seq bigint default 0;
alter table user_item_history_201002 add column c_seq bigint default 0;
alter table user_item_history_201003 add column c_seq bigint default 0;
alter table user_item_history_201004 add column c_seq bigint default 0;
alter table user_item_history_201005 add column c_seq bigint default 0;
alter table user_item_history_201006 add column c_seq bigint default 0;
alter table user_item_history_201007 add column c_seq bigint default 0;
alter table user_item_history_201008 add column c_seq bigint default 0;
alter table user_item_history_201009 add column c_seq bigint default 0;
alter table user_item_history_201010 add column c_seq bigint default 0;
alter table user_item_history_201011 add column c_seq bigint default 0;
alter table user_item_history_201012 add column c_seq bigint default 0;
alter table user_item_history_201101 add column c_seq bigint default 0;
alter table user_item_history_201102 add column c_seq bigint default 0;
alter table user_item_history_201103 add column c_seq bigint default 0;
alter table user_item_history_201104 add column c_seq bigint default 0;
alter table user_item_history_201105 add column c_seq bigint default 0;
alter table user_item_history_201106 add column c_seq bigint default 0;
alter table user_item_history_201107 add column c_seq bigint default 0;
alter table user_item_history_201108 add column c_seq bigint default 0;
alter table user_item_history_201109 add column c_seq bigint default 0;
alter table user_item_history_201110 add column c_seq bigint default 0;
alter table user_item_history_201111 add column c_seq bigint default 0;
alter table user_item_history_201112 add column c_seq bigint default 0;
alter table user_item_history_201201 add column c_seq bigint default 0;
alter table user_item_history_201202 add column c_seq bigint default 0;
alter table user_item_history_201203 add column c_seq bigint default 0;
alter table user_item_history_201204 add column c_seq bigint default 0;
alter table user_item_history_201205 add column c_seq bigint default 0;
alter table user_item_history_201206 add column c_seq bigint default 0;
alter table user_item_history_201207 add column c_seq bigint default 0;
alter table user_item_history_201208 add column c_seq bigint default 0;
alter table user_item_history_201209 add column c_seq bigint default 0;
alter table user_item_history_201210 add column c_seq bigint default 0;
alter table user_item_history_201211 add column c_seq bigint default 0;
alter table user_item_history_201212 add column c_seq bigint default 0;
alter table user_item_history_201301 add column c_seq bigint default 0;
alter table user_item_history_201302 add column c_seq bigint default 0;
alter table user_item_history_201303 add column c_seq bigint default 0;
alter table user_item_history_201304 add column c_seq bigint default 0;
alter table user_item_history_201305 add column c_seq bigint default 0;
alter table user_item_history_201306 add column c_seq bigint default 0;
alter table user_item_history_201307 add column c_seq bigint default 0;
alter table user_item_history_201308 add column c_seq bigint default 0;
alter table user_item_history_201309 add column c_seq bigint default 0;
alter table user_item_history_201310 add column c_seq bigint default 0;
alter table user_item_history_201311 add column c_seq bigint default 0;

-- c_seq
update itemshop.campaign_user t set c_seq = s.c_seq from basic.cardinfo s where t.c_seq = 0 and t.rfid = s.rfid and t.locale = lower(s.nationcode) ;
update itemshop.copyitem_user t set c_seq = s.c_seq from basic.cardinfo s where t.c_seq = 0 and t.rfid = s.rfid and t.locale = lower(s.nationcode) ;
update itemshop.custom t set c_seq = s.c_seq from basic.cardinfo s where t.c_seq = 0 and t.rfid = s.rfid and t.locale = lower(s.nationcode) ;
update itemshop.giveitem_checkrfid t set c_seq = s.c_seq from basic.cardinfo s where t.c_seq = 0 and t.rfid = s.rfid and t.locale = lower(s.nationcode) ;
update itemshop.item_present t set c_seq = s.c_seq from basic.cardinfo s where t.c_seq = 0 and t.rfid = s.rfid and t.locale = lower(s.nationcode) ;
update itemshop.user_item t set c_seq = s.c_seq from basic.cardinfo s where t.c_seq = 0 and t.rfid = s.rfid and t.locale = lower(s.nationcode) ;


/* sound resource*/
update item_locale set screenshot2='data/soundClips/S23_5.WAV' where itemid=3027;
update item_locale set screenshot2='data/soundClips/S23_6.WAV' where itemid=3035;
update item_locale set screenshot2='data/soundClips/S23_7.WAV' where itemid=3043;
update item_locale set screenshot2='data/soundClips/S23_2.WAV' where itemid=193;
update item_locale set screenshot2='data/soundClips/S23_1.WAV' where itemid=168;
update item_locale set screenshot2='data/soundClips/3667_2.wav' where itemid=3667;
update item_locale set screenshot2='thumbimg/screenshot/3668_2.wav' where itemid=3668;
update item_locale set screenshot2='data/soundClips/S23_3.WAV' where itemid=3010;
update item_locale set screenshot2='data/soundClips/S23_4.WAV' where itemid=3019;
update item_locale set screenshot2='data/soundClips/S23_8.WAV' where itemid=3051;

/* 정규 표현식 */
update item set screenshot2='' where screenshot2 ~ '^image' and categoryid=6

-- indexing
CREATE INDEX user_item_c_seq_i ON user_item USING btree ( c_seq );
CREATE INDEX campaign_user_c_seq_i ON campaign_user USING btree (c_seq);
CREATE INDEX custom_c_seq_i ON custom USING btree (c_seq);
CREATE INDEX giveitem_checkrfid_c_seq_i ON giveitem_checkrfid USING btree (c_seq);
CREATE INDEX item_present_c_seq_i ON item_present USING btree (c_seq);
CREATE INDEX item_present_to_c_seq_i ON item_present USING btree (to_c_seq);
CREATE INDEX user_item_history_c_seq_i ON user_item_history USING btree ( c_seq );

CREATE INDEX user_item_history_200901_c_seq_i ON user_item_history_200901 USING btree ( c_seq );
CREATE INDEX user_item_history_200902_c_seq_i ON user_item_history_200902 USING btree ( c_seq );
CREATE INDEX user_item_history_200903_c_seq_i ON user_item_history_200903 USING btree ( c_seq );
CREATE INDEX user_item_history_200904_c_seq_i ON user_item_history_200904 USING btree ( c_seq );
CREATE INDEX user_item_history_200905_c_seq_i ON user_item_history_200905 USING btree ( c_seq );
CREATE INDEX user_item_history_200906_c_seq_i ON user_item_history_200906 USING btree ( c_seq );
CREATE INDEX user_item_history_200907_c_seq_i ON user_item_history_200907 USING btree ( c_seq );
CREATE INDEX user_item_history_200908_c_seq_i ON user_item_history_200908 USING btree ( c_seq );
CREATE INDEX user_item_history_200909_c_seq_i ON user_item_history_200909 USING btree ( c_seq );
CREATE INDEX user_item_history_200910_c_seq_i ON user_item_history_200910 USING btree ( c_seq );
CREATE INDEX user_item_history_200911_c_seq_i ON user_item_history_200911 USING btree ( c_seq );
CREATE INDEX user_item_history_200912_c_seq_i ON user_item_history_200912 USING btree ( c_seq );
CREATE INDEX user_item_history_201001_c_seq_i ON user_item_history_201001 USING btree ( c_seq );
CREATE INDEX user_item_history_201002_c_seq_i ON user_item_history_201002 USING btree ( c_seq );
CREATE INDEX user_item_history_201003_c_seq_i ON user_item_history_201003 USING btree ( c_seq );
CREATE INDEX user_item_history_201004_c_seq_i ON user_item_history_201004 USING btree ( c_seq );
CREATE INDEX user_item_history_201005_c_seq_i ON user_item_history_201005 USING btree ( c_seq );
CREATE INDEX user_item_history_201006_c_seq_i ON user_item_history_201006 USING btree ( c_seq );
CREATE INDEX user_item_history_201007_c_seq_i ON user_item_history_201007 USING btree ( c_seq );
CREATE INDEX user_item_history_201008_c_seq_i ON user_item_history_201008 USING btree ( c_seq );
CREATE INDEX user_item_history_201009_c_seq_i ON user_item_history_201009 USING btree ( c_seq );
CREATE INDEX user_item_history_201010_c_seq_i ON user_item_history_201010 USING btree ( c_seq );
CREATE INDEX user_item_history_201011_c_seq_i ON user_item_history_201011 USING btree ( c_seq );
CREATE INDEX user_item_history_201012_c_seq_i ON user_item_history_201012 USING btree ( c_seq );
CREATE INDEX user_item_history_201101_c_seq_i ON user_item_history_201101 USING btree ( c_seq );
CREATE INDEX user_item_history_201102_c_seq_i ON user_item_history_201102 USING btree ( c_seq );
CREATE INDEX user_item_history_201103_c_seq_i ON user_item_history_201103 USING btree ( c_seq );
CREATE INDEX user_item_history_201104_c_seq_i ON user_item_history_201104 USING btree ( c_seq );
CREATE INDEX user_item_history_201105_c_seq_i ON user_item_history_201105 USING btree ( c_seq );
CREATE INDEX user_item_history_201106_c_seq_i ON user_item_history_201106 USING btree ( c_seq );
CREATE INDEX user_item_history_201107_c_seq_i ON user_item_history_201107 USING btree ( c_seq );
CREATE INDEX user_item_history_201108_c_seq_i ON user_item_history_201108 USING btree ( c_seq );
CREATE INDEX user_item_history_201109_c_seq_i ON user_item_history_201109 USING btree ( c_seq );
CREATE INDEX user_item_history_201110_c_seq_i ON user_item_history_201110 USING btree ( c_seq );
CREATE INDEX user_item_history_201111_c_seq_i ON user_item_history_201111 USING btree ( c_seq );
CREATE INDEX user_item_history_201112_c_seq_i ON user_item_history_201112 USING btree ( c_seq );
CREATE INDEX user_item_history_201201_c_seq_i ON user_item_history_201201 USING btree ( c_seq );
CREATE INDEX user_item_history_201202_c_seq_i ON user_item_history_201202 USING btree ( c_seq );
CREATE INDEX user_item_history_201203_c_seq_i ON user_item_history_201203 USING btree ( c_seq );
CREATE INDEX user_item_history_201204_c_seq_i ON user_item_history_201204 USING btree ( c_seq );
CREATE INDEX user_item_history_201205_c_seq_i ON user_item_history_201205 USING btree ( c_seq );
CREATE INDEX user_item_history_201206_c_seq_i ON user_item_history_201206 USING btree ( c_seq );
CREATE INDEX user_item_history_201207_c_seq_i ON user_item_history_201207 USING btree ( c_seq );
CREATE INDEX user_item_history_201208_c_seq_i ON user_item_history_201208 USING btree ( c_seq );
CREATE INDEX user_item_history_201209_c_seq_i ON user_item_history_201209 USING btree ( c_seq );
CREATE INDEX user_item_history_201210_c_seq_i ON user_item_history_201210 USING btree ( c_seq );
CREATE INDEX user_item_history_201211_c_seq_i ON user_item_history_201211 USING btree ( c_seq );
CREATE INDEX user_item_history_201212_c_seq_i ON user_item_history_201212 USING btree ( c_seq );
CREATE INDEX user_item_history_201301_c_seq_i ON user_item_history_201301 USING btree ( c_seq );
CREATE INDEX user_item_history_201302_c_seq_i ON user_item_history_201302 USING btree ( c_seq );
CREATE INDEX user_item_history_201303_c_seq_i ON user_item_history_201303 USING btree ( c_seq );
CREATE INDEX user_item_history_201304_c_seq_i ON user_item_history_201304 USING btree ( c_seq );
CREATE INDEX user_item_history_201305_c_seq_i ON user_item_history_201305 USING btree ( c_seq );
CREATE INDEX user_item_history_201306_c_seq_i ON user_item_history_201306 USING btree ( c_seq );
CREATE INDEX user_item_history_201307_c_seq_i ON user_item_history_201307 USING btree ( c_seq );
CREATE INDEX user_item_history_201308_c_seq_i ON user_item_history_201308 USING btree ( c_seq );
CREATE INDEX user_item_history_201309_c_seq_i ON user_item_history_201309 USING btree ( c_seq );
CREATE INDEX user_item_history_201310_c_seq_i ON user_item_history_201310 USING btree ( c_seq );
CREATE INDEX user_item_history_201311_c_seq_i ON user_item_history_201311 USING btree ( c_seq );
CREATE INDEX user_item_history_201312_c_seq_i ON user_item_history_201312 USING btree ( c_seq );



-- DB 이관 Script
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'admin_user', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'admin_user_log', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'campaign_info', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'eventitem', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'giveitem_checkrfid', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'campaign_user', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'copyitem_user', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'custom', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'event', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_machine_event', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_count', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_event', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_export', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_locale', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_locale_tag', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_mapping_es', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_mapping_fr', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_mapping_hk', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_mapping_kr', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_mapping_pt', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_mapping_sg', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_mapping_tw', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_mapping_us', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_set', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_present', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_price', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'item_resource', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'itemcategory', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'machine_event', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'promotion', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'promotion_item', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'randomitem', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'randomitem_item', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'resource', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'shop_item_change_request', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'shop_item_request', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200901', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200902', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200903', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200904', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200905', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200906', 'phenix_mgdb', 'px`rogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200907', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200908', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200909', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200910', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200911', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_200912', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201001', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201002', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201003', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201004', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201005', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201006', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201007', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201008', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201009', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201010', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201011', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201012', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201101', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201102', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201103', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201104', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201105', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201106', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201109', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201107', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201110', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201108', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201111', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201112', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201201', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201202', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201204', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201203', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201205', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201206', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201207', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201208', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201209', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201210', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201211', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201212', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201301', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201302', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201303', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201304', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201305', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201306', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201307', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201308', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201309', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201310', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_201311', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_history_stat', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_one_table('phoenix', 'itemshop', 'user_item_sell_history', 'phoenix_mgdb', 'pxprogram');
SELECT zz_korine.sp_migration_all_seq('phoenix', 'itemshop', 'phoenix_mgdb', 'pxprogram');



